### ISSUE TITLE
Can be integrated with Unity toolkit 

### ISSUE THREAD

**Issue by AladdinHZ** [ssatguru/BabylonJS-CharacterController#20]
Hello Guys, great work!, can the library used in unity to integrated with current project ?

**Comment by ssatguru** [comment]
@AladdinHZ 
Thanks
If you are referring to Unity WebGL Target then the answer to is no. Unity WebGL uses its own  webgl engine. This character controller is meant to be used with Babylonjs WebGL engine.
If you are referring to the Babylonjs Unity exporter (https://doc.babylonjs.com/resources/intro) then the answer is probably yes but confirm with MackeyK24 on babylonjs forum.
