### ISSUE TITLE
testAnimationGroup from GLB not working

### ISSUE THREAD

**Issue by bigrig2212** [ssatguru/BabylonJS-CharacterController#47]
Hi - just downloaded, npm installed and clicked "test animation group (using a .glb file)" 
Character moves around, but does not change animation state (frozen state). 
Haven't dived into it yet... but that's what i get on first install. 
Works fine in .babylon format.

**Comment by bigrig2212** [comment]
Is there supposed to be something that gets set here to make the GLBs work in CharacterController?
<img width="522" alt="Screen Shot 2022-02-21 at 12 53 22 PM" src="https://user-images.githubusercontent.com/19869387/155025121-63a20cb2-2251-446d-9790-46a025b05659.png">

**Comment by bigrig2212** [comment]
Or maybe that the anim.exist objects are set to false? 
<img width="528" alt="Screen Shot 2022-02-21 at 1 21 54 PM" src="https://user-images.githubusercontent.com/19869387/155028506-0d6dde9c-d643-41a1-9a02-e3f9a3980b74.png">

**Comment by echan00** [comment]
@bigrig2212 have you had any luck? also have the same question

**Comment by ssatguru** [comment]
@bigrig2212 
Sorry was away and missed this.
You are right , I must have broken something.
@echan00 
Thanks for looking into this and the fix

Hopefully I can get to this by end of this week.

**Comment by ssatguru** [comment]
@bigrig2212 @echan00 
This should be fixed.
The previous version (0.4.3) constructor took AnimationGroup as a parameter
The new alpha version constructor can take a ActionMap/AnimationGroup as parameter
A bug broke backward compatibility.
Have now fixed that bug.

Next time I will build alpha versions in their own branch so as to not break existing test/demos.

Please test and close if it works for you.

**Comment by bigrig2212** [comment]
Yay, your fix works great. This sample was key to getting it working: https://github.com/ssatguru/BabylonJS-CharacterController/blob/master/tst/testAnimationGroup.js
