### ISSUE TITLE
What about pull requests awaiting review ?

### ISSUE THREAD

**Issue by dad72** [ssatguru/BabylonJS-CharacterController#57]
I see PRs that have not been validated for some time and have even become obsolete.

I have done 2 PRs recently awaiting review. Is the CharacterControler still maintained ?

Thanks

**Comment by dad72** [comment]
? @ssatguru Did you drop this CharacterController project ?

**Comment by ssatguru** [comment]
Sorry, been busy. Haven't looked at this for a while. Will have a look soon

**Comment by dad72** [comment]
ok
