### ISSUE TITLE
Bug with lesson animation + jump

### ISSUE THREAD

**Issue by dad72** [ssatguru/BabylonJS-CharacterController#8]
Hi,

When you walk while jumping, it works, but if you run, you can't jump at the same time.

Thanks

**Comment by dad72** [comment]
I just understood by testing your Demo that only the jump animation works while running.

My model has no animation on the jump. But it jumps anyway when we walk (at least it is move on the Y axis) But not when we run.

It was just to clarify.

**Comment by ssatguru** [comment]
Hi @dad72 ,
With version 2.0 I added 2 jumps "idleJump" and "runJump" .
"idleJump" plays when avatar is idle. 
"runJump" plays while walking, running etc.
Instead of "runJump"  maybe I should have called it just "jump" :(
Thanks

**Comment by dad72** [comment]
My runJum doesn't work. I do not know why ?
I'm not talking about the animations, but about moving along the Y axis. When I run, I can't jump.

**Comment by ssatguru** [comment]
Can you provide a test/demo?

**Comment by dad72** [comment]
No I have no online tests currently, my project is local

**Comment by ssatguru** [comment]
Jump should work during walking and running. 
In the demo it works.
Until i see your code I can't say why it does not work for you.

**Comment by dad72** [comment]
In the demo, the jump animation works when you walk and run.

I don't have jump animation. When I walk, the character is moving from the ground on the Y axis, but not when I run. I think it's done using more than 2 keyboard keys at a time. Only two simultaneous keys seem to work

I also noticed that when the character jumps from a mountain into the void, the animation remains blocked in the void until it touches the ground.

**Comment by dad72** [comment]
Ok, I made you a test file online.

1) The jump bug from what I understand, this product as soon as: cc.setWalkKey("Z");
If I change the keyboard key, the jump no longer works (if I leave by default with W it works.
**In this online demo the key is W**

2) You can also see that the character is facing me now and even if I put: 
_cc.setFaceForward(false);
cc.setMode(0);_
The character still faces me. No changes. It worked well before yesterday's update

3) Try to run into space, then release the keys on the keyboard. You can see that the character continues to run through the void until it hits the ground. **I would like a change of animation when it jumps into the void (a dive for example like a parachute jump)** There the animation remains blocked on : walk or run.

4) Gravity also doesn't seem to be high enough. Logically a gravity is around 9.81. There I see putting 98.1 so that gravity is more coherent. It's huge, but correct. If I put 9.8, the character takes a long time to hit the ground

I hope this helps you see better.

Online:
http://www.babylon.actifgames.com/characterController/index.html
Zip:
http://www.babylon.actifgames.com/characterController/tst.zip

Thank you for this CharacterController

**Comment by ssatguru** [comment]
Thanks for the test file. It helped me catch some nasty bugs :)

1) The keys have to be in specified in caps. "W" not "w", "Z" not "z"
2) fixed cc.setFaceForward(false) and cc.setMode(0)
3) fixed. the character would now play the "fall" animation
4) 9.81 is probably low for games but  physics correct.  As people can easily change this ,I would leave it as is for now.
Attached is your test file with the new charactercontroller.
[tst.zip](https://github.com/ssatguru/BabylonJS-CharacterController/files/4520190/tst.zip)

**Comment by dad72** [comment]
1. I did use capital letters for letters in the demo (cc.setWalkKey("Z");). I must have explained it wrong. If by default (W) the jump works in running. But if I change it with Z (use capital letters). it no longer works the jump in running. 
Try it on the demo. Comment the line 79: setWalkKey ('Z') The jump will be good. Uncomment, the jump will no longer run while running.

2. Fixe, yes

3. I still have the same problem. I may have expressed myself badly again. Put yourself on top of the mountain at the highest. Run towards the edge. When you are in a vacuum, release the keyboard, the Run animation continues until the character hits the ground. 
If we want the character to jump by parachute or others, the character runs in the void.

4. I understand for this one, it is not a major problem.

**Comment by dad72** [comment]
Ok, for 2). Fixed.

For 1). Yes at my place, no running jump. It works if you leave the default 'W' key for the same demo I sent you.
Are we talking about the same thing? If you press space, you can see the character take off from the ground?
Same thing when you walk. But when we run, nothing, the character 'Run', but do not 'Jump' if I change the key to W by default. I also don't understand why this is happening.

For 5). Do you have trouble understanding what I'm writing? I use a translator to write in English, so you may not understand the translation well.
If I click on Q to slide to the right (I'm not talking about turning right), then after I run, the character runs, but also trembles while trying to slide to the right. Which is not normal. There is actually a bug here that didn't happen before

**Comment by dad72** [comment]
I tried another keyboard key using 'R' to walk and run. The strange thing is that it works to also jump while running. Only with the redefined 'Z' key which prevents the jump in current. Yes, it’s strange, I don’t explain it. Ideas ? What does it have my Z key (It works however because my character walks and runs)

**Comment by dad72** [comment]
Ok, I'm starting to understand. I find what is wrong I think.

To make it work, I press Z then SHIFT then SPACE and release SHIFT to get the jump.
If I click on SPACE last it will not work, I must then release SHIFT to get the jump. 

Is this normal? If I have more than 3 keys using Z, the jump does not work.

I also change this in your code:  ( in _onKeyDown(e) and  _onKeyUp(e) )

e = e || window.event;
const code = e.which || e.keyCode;
const chr = String.fromCharCode(code);

I also add the TAB key to lock the run and the runing and jump character.

**Comment by dad72** [comment]
Another bug is that when you keep the spacebar pressed, the jump is done several times. Shouldn't it be done only once, even if you keep the space key pressed?

Also if I press Z to walk, then Shift to run and I release both keys at the same time, the character walks without any keys to activate.

**Comment by dad72** [comment]
I close this problem which is partly solved.
